/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author romme
 */
public class LoginStudent extends javax.swing.JPanel {

    /**
     * Creates new form LoginStudent
     */
    public LoginStudent() {
        initComponents();
        jRadioButton2.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(766, 732));
        setMinimumSize(new java.awt.Dimension(766, 732));
        setPreferredSize(new java.awt.Dimension(766, 732));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("class time");
        add(jLabel2);
        jLabel2.setBounds(160, 50, 108, 46);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Name of subject: ");
        add(jLabel3);
        jLabel3.setBounds(20, 120, 120, 33);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Group:");
        add(jLabel4);
        jLabel4.setBounds(70, 160, 56, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Start Time:");
        add(jLabel5);
        jLabel5.setBounds(50, 200, 79, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("End Time:");
        add(jLabel6);
        jLabel6.setBounds(60, 240, 71, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Day of class:");
        add(jLabel7);
        jLabel7.setBounds(35, 280, 90, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("is elective subject?:");
        add(jLabel8);
        jLabel8.setBounds(190, 330, 127, 25);

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setText("Yes");
        add(jRadioButton1);
        jRadioButton1.setBounds(100, 370, 98, 25);

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("No");
        add(jRadioButton2);
        jRadioButton2.setBounds(310, 370, 98, 25);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(140, 120, 277, 27);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField2);
        jTextField2.setBounds(140, 160, 277, 30);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField3);
        jTextField3.setBounds(140, 200, 277, 26);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField4);
        jTextField4.setBounds(140, 240, 277, 26);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField5);
        jTextField5.setBounds(140, 280, 277, 26);

        jButton1.setText("Aceptar");
        add(jButton1);
        jButton1.setBounds(190, 440, 72, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton2;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
