/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import herramientas.ControlInter;
import java.awt.Dimension;

/**
 *
 * @author ledrc
 */
public class Menu extends javax.swing.JPanel implements ControlInter
{

    
    /**
     * Creates new form Menu
     */
    
    Dimension dim;
    
    public Menu(Dimension dim)
    {
        initComponents();
        this.dim = dim;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void expandir(Dimension dim)
    {
        this.dim = dim;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
